#ifndef REACHY_H
#define REACHY_H

typedef enum
{
    // DXL
    // From PC -> Dxl
    MSG_TYPE_DXL_GET_REG = 10, // [MSG_TYPE_DXL_GET_REG, DXL_REG, NB_BYTES, (DXL_ID)+]
    MSG_TYPE_DXL_SET_REG = 11, // [MSG_TYPE_DXL_SET_REG, DXL_REG, NB_BYTES, (DXL_ID, VAL_H, (VAL_L)*)+]

    // From Dxl --> PC
    MSG_TYPE_DXL_PUB_DATA = 15, // [MSG_TYPE_DXL_PUB_DATA, DXL_REG, NB_BYTES, (DXL_ID, ERR1, ERR2, (VAL)+)+]

    // LOAD sensor
    MSG_TYPE_LOAD_PUB_DATA = 20, // [MSG_TYPE_LOAD_PUB_DATA, (ID, FLOAT)+]

    // FAN
    // From PC -> Fan
    MSG_TYPE_FAN_GET_STATE = 30, // [MSG_TYPE_FAN_GET_STATE, (FAN_ID)+]
    MSG_TYPE_FAN_SET_STATE = 31, // [MSG_TYPE_FAN_SET_STATE, (FAN_ID, STATE)+]
    // From Fan --> PC
    MSG_TYPE_FAN_PUB_DATA = 35, // [MSG_TYPE_FAN_PUB_DATA, (FAN_ID, STATE)+]

    // Force Sensor
    MSG_TYPE_FORCE_SENSOR_PUB = 40, // [MSG_TYPE_FORCE_SENSOR_GET_VAL, SENSOR_ID, VAL]

    // Orbita
    // PC -> Orbita
    MSG_TYPE_ORBITA_GET_REG = 50, // [MSG_TYPE_ORBITA_GET_REG, ORBITA_ID, REG_TYPE]
    MSG_TYPE_ORBITA_SET_REG = 51, // [MSG_TYPE_ORBITA_SET_REG, ORBITA_ID, REG_TYPE, (MOTOR_ID, (VAL+))+]

    // Orbita -> PC
    MSG_TYPE_ORBITA_PUB_DATA = 55, // [MSG_TYPE_ORBITA_PUB_DATA, ORBITA_ID, REG_TYPE, (VAL1)+, (VAL2)+, (VAL3)+]

    // SYSTEM
    MSG_TYPE_KEEP_ALIVE = 200, // [MSG_TYPE_KEEP_ALIVE]

    MSG_DETECTION_GET_NODES = 210, // [MSG_DETECTION_GET_NODES]
    MSG_DETECTION_GET_CONTAINERS = 211, // [MSG_DETECTION_GET_CONTAINERS, (NODE_ID)+]
    MSG_DETECTION_GET_CONTAINER_INFO = 212, // [MSG_DETECTION_GET_CONTAINER_INFO, (CONTAINER_ID)+]
    MSG_DETECTION_PUB_NODES = 215, // [MSG_DETECTION_PUB_NODES, (NODE_ID)+]
    MSG_DETECTION_PUB_CONTAINERS = 216, // [MSG_DETECTION_PUB_CONTAINERS, NODE_ID, (CONTAINER_ID)+]
    MSG_DETECTION_PUB_CONTAINER_INFO = 217, // [MSG_DETECTION_PUB_CONTAINER_INFO, CONTAINER_ID, TYPE, ALIAS]

    MSG_MODULE_ASSERT = 222, // [MSG_MODULE_ASSERT, CHAR1, CHAR2, ...]
} msg_type_t;

#endif